// pages/about.tsx
import React, { Fragment } from 'react';
import Head from 'next/head';
import styled from 'styled-components';

import { HoverLink } from '../styles/util';

const Container = styled.main`
  display: flex;
  flex-direction: column;
  max-width: 48rem;
  margin: 8rem auto;
  padding: 3rem;
  color: ${({ theme }) => theme.colors.white};
  background-color: ${({ theme }) => theme.colors.blue_800}EE;

  p {
    margin: 0;
    line-height: 1.5;
  }
`

const Title = styled.h1`
  margin: 0 0 2rem 0;
  color: ${({ theme }) => theme.colors.gray_50};
`

function OutsideLink({ children, href, ...rest }) {
  return <HoverLink href={href} target="_blank" rel="noopener noreferrer" {...rest}>{children}</HoverLink>
}

export default function AboutPage() {
  return (
    <Fragment>
      <Head>
        <Title>What Did Congress Do Today? - About</Title>
      </Head>
      <Container>
        <Title>About</Title>
        <p>
          What exactly goes on in a typical day at the Senate or the House of Representatives?
          I had no idea, but I wanted to find out. Staying informed about the political process
          is part of being a good citizen, but it can be hard to trawl through the Senate or House
          official websites to get the important information. This site was built to pull that
          information and display it in an easy-to-read format that provides the stuff
          people may actually care about. 
        </p>
        <h3>If you found this interesting, you can share it on Facebook or Twitter.</h3>
        <h3>Credits &amp; Attribution</h3>
        <p>The source code for the site is available on GitHub <OutsideLink href="https://github.com/njgingrich/whatdidcongressdo">here.</OutsideLink></p>
        <p>This site uses the great work of the <OutsideLink href="https://projects.propublica.org/api-docs/congress-api/">ProPublica Congress API</OutsideLink>.</p>
        <p>Main background image is public domain, <OutsideLink href="http://www.acclaimimages.com/_gallery/_pages/0519-1001-2819-3420.html">found here.</OutsideLink></p>
        <p>The SVG background is from heropatterns.com, licensed under CC 4.0.</p>
        <p>All times are in Eastern Standard Time (as Washington, D.C. is in EST).</p>
      </Container>
    </Fragment>
  )
}

// pages/about.vue
<template>
  <section class="container">
    <Navbar/>
    <section class="content">
      <h1 class="content-title">About the Site</h1>
      <p class="content-info">
        I developed this site because I wanted an easy way to see what exactly Congress is doing every day, and to make it easy for others to see the process that goes on in the Senate and the House.
      </p>
      <p class="content-sub-info">
        This site runs off of the <a href="https://projects.propublica.org/api-docs/congress-api/" target="_blank" rel="noopener">ProPublica Congress API</a>, and is updated approximately every hour.
      </p>
      <section class="share">
        <a href="#top" @click="fbPopup">Facebook</a>
        <a href="#top" @click="twitterPopup">Tweet</a>
      </section>
    </section>
  </section>
</template>
<script>
import Navbar from '~/components/Navbar'

export default {
  components: {
    Navbar
  },
  methods: {
    fbPopup () {
      // eslint-disable-next-line
      FB.ui({
        method: 'feed',
        display: 'popup',
        link: 'http://whatdidcongressdo.today',
        caption: 'An example caption'
      }, function (response) {})
    },
    twitterPopup () {
      window.open('https://twitter.com/intent/tweet?text=Find%20out%20what%20Congress%20is%20doing%20today.&url=http://whatdidcongressdo.today', '', 'width=640,height=420')
    }
  },
  mounted () {
    this.$initFBSDK()
  }
}
</script>
<style lang="scss" scoped>
@import "~assets/styles/colors";

.container {
  display: grid;
  grid-template-columns: auto minmax(auto, 1000px) auto;
  grid-template-rows: 56px auto;
  grid-template-areas:
  ". navbar  ."
  ". content .";

  background-image: url("~assets/images/congress.jpg");
  background-position-x: 50%;
  background-size: cover;
  height: 100vh;
}

.content {
  grid-area: content;
  align-self: start;
  margin: 64px;
  padding: 32px;
  background-color: $blue;
  color: $white;

  font-family: 'Merriweather';
}

.content-title {
  font-size: 32px;
  margin-top: 0;
}

.content-info {
  font-size: 16px;
}

.content-sub-info {
  font-size: 14px;
}

a, a:visited, a:active {
  color: $white;
}
</style>
